language: node_js
node_js:
  - "6"
  - "8"
brancher:
  only:
    - "dev"
    - "master"
install:
  - "npm install"
  - "npm install -g codecov"
script:
  - "istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec"
  - "codecov"